### ISSUE TITLE
NGX_OMNIAUTH_GOOGLE_HD does not work with prebuilt docker image

### ISSUE THREAD

**Issue by minimum2scp** [sorah/nginx_omniauth_adapter#1]
I tried to use prebiult docker image (https://quay.io/repository/sorah/nginx_omniauth_adapter)
with google_oauth2 provider like this docker-compose.yml:

```yaml
version: '2'
services:
  nginx_omniauth_adapter:
    container_name: nginx_omniauth_adapter
    image: quay.io/sorah/nginx_omniauth_adapter:latest
    environment:
      - NGX_OMNIAUTH_SESSION_SECRET=******
      - NGX_OMNIAUTH_HOST=http://nginx-omniauth-adapter.example.com
      - NGX_OMNIAUTH_GOOGLE_KEY=*******.apps.googleusercontent.com
      - NGX_OMNIAUTH_GOOGLE_SECRET=******
      - NGX_OMNIAUTH_GOOGLE_HD=example.com
    ports:
      - "8080:8080"
```

Authentication works, but domain restriction by `NGX_OMNIAUTH_GOOGLE_HD=example.com` does not work.

Updating omniauth-google-oauth2 gem solves this problem.

```shell
docker exec -ti nginx_omniauth_adapter bundle update omniauth-google-oauth2 # 0.2.8 -> 0.4.1
docker restart nginx_omniauth_adapter
```

quay.io/sorah/nginx_omniauth_adapter:latest includes omniauth-google-oauth2 0.2.8,
but, maybe omniauth-google-oauth2 [0.3.1](https://github.com/zquestz/omniauth-google-oauth2/blob/master/CHANGELOG.md#031---2016-01-28) or later is required.
